### ISSUE TITLE
push_image_and_stages pushes twice

### ISSUE THREAD

**Issue by oreporan** [whoan/docker-build-with-cache-action#102]
Hi,
I'm building a multi stage docker image.
The final image I want to upload to ECR and I've provided a `image_name` and `image_tag`.
However I would like to **not** push the `*-stages` image as well..

What is happening right now is that its pushing to image to ECR (not with the same IMAGE_ID)
> The push refers to repository [***.dkr.ecr.us-west-2.amazonaws.com/my_image:latest]
> The push refers to repository [***.dkr.ecr.us-west-2.amazonaws.com/my_image-stages]

```yml
      - name: build and deploy image
        uses: whoan/docker-build-with-cache-action@v5
        env:
          IMAGE_TAG: ${{ env.GITHUB_REF_SLUG }}_${{ env.VERSION }}.${{ env.GITHUB_SHA_SHORT }}
          IMAGE_TAG_LATEST: ${{ env.GITHUB_REF_SLUG }}
        with:
          registry: ${{ env.AWS_DEFAULT_REGISTRY_URL }}
          dockerfile: devops/deploy/d-id-worker/d-id-worker.Dockerfile
          image_name: ${{ env.REPO_PREFIX }}
          push_git_tag: true
          image_tag: ${{ env.IMAGE_TAG }},${{ env.IMAGE_TAG_LATEST }}
          build_extra_args: "--pull=false"

```
