### ISSUE TITLE
Issue running container locally

### ISSUE THREAD

**Issue by pwerth** [whoan/docker-build-with-cache-action#105]
I am using this library to build an image from a GHCR cache, as follows:

```
-  name: Build Tests Image
   uses: whoan/docker-build-with-cache-action@v5
   with:
    registry: ghcr.io
    username: ${{ github.actor }} 
    password: ${{ secrets.GHCR_TOKEN }}
    image_name: my-test-image
    image_tag: latest
```

I then want to run the container as part of my workflow:

```
-  name: Run Tests
   run: docker run my-test-image
```

However, this yields `docker: Error response from daemon: pull access denied for my-test-image, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.`

What is the proper syntax to run the image that is built from the caching step?
