### ISSUE TITLE
Does this work with services?

### ISSUE THREAD

**Issue by joshuarobs** [whoan/docker-build-with-cache-action#11]
I have a postgres server that's initialised like this in the yaml file:

````
jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

````

Is it possible to cache this, and if so, how?
