### ISSUE TITLE
docker cache and no cache set as variable

### ISSUE THREAD

**Issue by vipul-06** [whoan/docker-build-with-cache-action#124]
```
stage: Build Image
  script:
    - echo "$MY_DEV" > dev_key.json
    - sudo gcloud auth activate-service-account --project $PROJECT_ID_DEV --key-file=dev_key.json
    - sudo gcloud auth configure-docker
    - echo Building the Docker image...
    - sudo docker build --no-cache -t gcr.io/$PROJECT_ID_DEV/$IMAGE_NAME:$IMAGE_TAG --file Dockerfile .
    - sudo docker push gcr.io/$PROJECT_ID_DEV/$IMAGE_NAME:$IMAGE_TAG
  only:
    - develop
  tags:
    - my-runner-ci
```

I have my pipeline written like above to build image , In this the docker build command by default uses no cache so pipeline is build from start everytime, I want to set an option that by default "docker build should use cache" and want to use no cache manually only whenever I want . I was looking if I can set --no-cache as a variable and then pass by writing some rules? Or any other method if anyone can suggest
