### ISSUE TITLE
Support for YAML anchors and aliases?

### ISSUE THREAD

**Issue by why-not-try-calmer** [whoan/docker-build-with-cache-action#128]
I would seem that, as of the latest version, this action doesn't support anchors and aliases. For example if, in my `docker-compose.yml` file, I define a service as:

```yaml
  service1: &service1-config
  service2:
    <<: *service1-config
```

the action will throw on the alias (`<<`). Is there any plan to support this syntactical feature in an upcoming release?
