### ISSUE TITLE
Could not log in (please check credentials)

### ISSUE THREAD

**Issue by v0ldemar01** [whoan/docker-build-with-cache-action#132]
Hey everyone. I followed [this documentation](https://github.com/whoan/docker-build-with-cache-action/blob/master/README.md) and also the [examples](https://github.com/whoan/hello-world/tree/master/.github/workflows) to setup the configuration of build and push docker image to private ECR via role assumption.
That is my configuration:
```yml
name: Continuous Delivery Development

on:
  pull_request:
    branches:
      - development
      - production

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ secrets.AWS_REGION }}

      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1

      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity

      - name: Build, tag, and push backend image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          image_name: ${{ secrets.ECR_BACKEND_REPOSITORY }}
          registry: ${{ secrets.ECR_REGISTRY }}
          image_tag: ${{ github.sha }}
          context: ./
          dockerfile: ./backend/Dockerfile.development
```
But I got erros on 
      - name: Build, tag, and push backend image
<img width="1161" alt="image" src="https://github.com/whoan/docker-build-with-cache-action/assets/43109766/4db001e0-0220-4897-afe4-f8c32a6b6776">
I was trying to debug it via adding Hello from AWS: WhoAmI and it works fine. These errors appear regardless of Login to Amazon ECR step. I've tried to assign a maximum level of permissions to the role but it didn't help.
Can you please assist me?
