### ISSUE TITLE
When using <folder>/docker-compose.yaml, the context is not relative to <folder>

### ISSUE THREAD

**Issue by Clashsoft** [whoan/docker-build-with-cache-action#133]
I have a folder structure like this:

```
foo
+ bar
|  + Dockerfile
+ docker-compose.yaml
baz ...
```

So my Dockerfile is at `foo/bar/Dockerfile` and the `compose_file` at `foo/docker-compose.yaml` with the contents:

```yaml
services:
  bar:
    image: bar
    build:
      context: .
      dockerfile: bar/Dockerfile
```

The action step is:

```yaml
      - name: Build
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          context: foo/ # hopeless attempt
          compose_file: foo/docker-compose.yaml
```

When working locally in `bar`, for example using `docker compose build`, the context and Dockerfile are correct. But this action will run the command `docker build -t bar -f ./bar/Dockerfile` in the root directory! So the `foo` folder is completely ignored, and the command will fail.

I propose either respecting the `context` action argument even when using `compose_file`, or making the context relative to the parent directory of the `compose_file`.
