### ISSUE TITLE
compose_file ignored build args

### ISSUE THREAD

**Issue by Clashsoft** [whoan/docker-build-with-cache-action#134]
Simple example:

```yaml
services:
  bar:
    image: bar
    build:
      context: .
      args:
        FOO: bar
```

The command is just `docker build -t bar -f ./Dockerfile`, no `--build-arg FOO=bar` or anything.
