### ISSUE TITLE
Cannot login to ECR

### ISSUE THREAD

**Issue by viyullas** [whoan/docker-build-with-cache-action#15]
When I try to use your action against the AWS registry (ECR) I get this message:

Error response from daemon: login attempt to https://***.dkr.ecr.eu-central-1.amazonaws.com/v2/ failed with status: 401 Unauthorized

Do you have any running example with AWS? Or is there something than prevents this action to work with it?

Follows my configuration:
    - uses: whoan/docker-build-with-cache-action@v3
      with:
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        image_name: XXXXXXXXX.dkr.ecr.eu-west-1.amazonaws.com/repo-name
        image_tag: dev
        registry: XXXXXXXXX.dkr.ecr.eu-west-1.amazonaws.com
        context: repo-name

**Comment by whoan** [comment]
Hi @viyullas . I didn't try with AWS, I thought you need `aws-cli` to login to registry so I didn't want to add more complexity to the script because of that. I can try at the weekend and let you know.

**Comment by viyullas** [comment]
There is an action to make the login (aws-actions/amazon-ecr-login@v1), but I could not manage to make it work even after executing this action.

**Comment by whoan** [comment]
Can you successfully  `docker login` to AWS ECR from your console with those credentials? Just to discard any problem with the creds.

**Comment by viyullas** [comment]
You don't "docker login" to ECR, you have to login using aws-cli and then you can interact with ECR again using aws-cli
I am using another action that seems to do the trick "devmasx/cached-docker-build-push"

**Comment by whoan** [comment]
Yes, that was my guess, that you can't login to AWS ECR with `docker login`. For that reason, this action doe snot support to login to ECR for the moment.

Maybe in the future. I am glad you found that action to make it work. Thanks.

Closing this one.

**Comment by mmattosr** [comment]
Actually its possible tu use this aproach: https://aws.amazon.com/pt/blogs/compute/authenticating-amazon-ecr-repositories-for-docker-cli-with-credential-helper/

I'll try to make a PR in my free time with this.

**Comment by jbarop** [comment]
`ecr get-login` is deprecated and got replaced with `ecr-get-login-password`.

This works for me:

```
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Get AWS ECR credentials
      id: ecr-credentials
      run: |
        echo "::set-output name=username::AWS"
        echo "::set-output name=password::`aws ecr get-login-password`"

    - name: Docker build
      uses: whoan/docker-build-with-cache-action@master
      with:
        username: ${{ steps.ecr-credentials.outputs.username }}
        password: ${{ steps.ecr-credentials.outputs.password }}
        registry: ${{ secrets.AWS_ECR_REGISTRY }}
        image_name: some-image-name
```
