### ISSUE TITLE
Supplying AWS creds but still getting missing username warning

### ISSUE THREAD

**Issue by bagedevimo** [whoan/docker-build-with-cache-action#153]
When running this action after the `aws-actions/configure-aws-credentials` action, variables are set but the docker-build-with-cache-action doesn't seem to be detecting them? Possibly because i'm using OIDC login so i'm not explicitly setting those variables?

```    - name: Configure AWS creds
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.ECR_IAM_ROLE_TO_ASSUME }}
        aws-region: ap-southeast-2
```

Output: 
```
Run whoan/docker-build-with-cache-action@v8.0.2
  with:
    registry: 224854405218.dkr.ecr.ap-southeast-2.amazonaws.com/delivereasy/core
    image_name: some-build
    image_tag: d75c5b8136235f61cc692f96c1e5b7914566a3c5
    services_regex: .+
    context: .
    dockerfile: Dockerfile
    push_image_and_stages: true
    push_git_tag: false
    pull_image_and_stages: true
  env:
    AWS_DEFAULT_REGION: ap-southeast-2
    AWS_REGION: ap-southeast-2
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***
```
