### ISSUE TITLE
image name/tag not working

### ISSUE THREAD

**Issue by nolazybits** [whoan/docker-build-with-cache-action#24]
Passing an image name and tag is not working.
```
      - name: Build and Cache Develop Image
        uses: whoan/docker-build-with-cache-action@v4
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: base.dockerfile
          context: .docker
          image_name: nodebrick/nodebrick-develop
          image_tag: ${{ env.DEBIAN_VERSION }}-${{ env.NODE_VERSION }}
          push_image_and_stages: false
          build_extra_args: "--build-arg PROJECT_ID=${{ env.PROJECT_ID }} --build-arg DEBIAN_VERSION=${{ env.DEBIAN_VERSION }} --build-arg NODE_VERSION=${{ env.NODE_VERSION }}"
```

Logs
```
[Action Step] Building image...
+ docker build --tag my_awesome_image --file .docker/base.dockerfile --build-arg PROJECT_ID=nodebrick --build-arg DEBIAN_VERSION=buster-slim --build-arg NODE_VERSION=current .docker
```

Action can be seen in action here
https://github.com/nodebrick/nodebrick/runs/502276509?check_suite_focus=true

Workaround is adding the `--tag` arg in the build_extra_args
`--tag ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}-develop:${{ env.DEBIAN_VERSION }}-${{ env.NODE_VERSION }} `
