### ISSUE TITLE
Use 7 chars of GitHub SHA in tag name 

### ISSUE THREAD

**Issue by riker09** [whoan/docker-build-with-cache-action#49]
I want to tag my images with the first 7 characters of the Git(Hub) SHA.

After looking through the issues here I came across https://github.com/whoan/docker-build-with-cache-action/issues/28#issuecomment-615014124 and came up with this (simplified) GitHub Actions workflow:

```yaml
jobs:
  my-job:
    runs-on: ubuntu-18.04

    env:
      SHA7: "${GITHUB_SHA:0:7}"

    steps:
    - uses: actions/checkout@v2

    - uses: whoan/docker-build-with-cache-action@v5
      with:
        image_name: my-image
        image_tag: "latest,foo-${SHA7}"
        build_extra_args: --build-arg FOO=Bar
        dockerfile: path/to/Dockerfile
        username: ***
        registry: docker.pkg.github.com
        password: "${{ secrets.GITHUB_TOKEN }}"
```

This results in this error:

```
Tagging: foo-${SHA7}
Error parsing reference: "docker.pkg.github.com/<ORGANIZATION>/<REPOSITORY>/my-image:foo-${SHA7}" is not a valid repository/tag: invalid reference format
```

**Comment by riker09** [comment]
I have found a workaround [here](https://github.community/t/add-short-sha-to-github-context/16418/11).

It consists of creating output with an additional step and using that named output later on:

```yaml
jobs:
  my-job:
    runs-on: ubuntu-18.04

    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"

    - uses: whoan/docker-build-with-cache-action@v5
      with:
        image_name: my-image
        image_tag: "latest,foo-{{ steps.slug.outputs.sha7 }}"
```
