### ISSUE TITLE
Multiple tags not working?

### ISSUE THREAD

**Issue by nloui** [whoan/docker-build-with-cache-action#56]
I've setup my config to push multiple tags on subsequent builds:
```
name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2
      - name: Build and push docker
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.GH_PACKAGES_USER }}
          password: ${{ secrets.GH_PACKAGES_TOKEN }}
          registry: docker.pkg.github.com
          image_name: ${{ github.repository_owner }}/${{ github.event.repository.name }}/${{ github.event.repository.name }}
          image_tag: latest,${{ github.sha }}

```

But it appears that the "latest" tag doesn't ever update.  New builds push out with the new github sha.  Am I missing something?
