### ISSUE TITLE
Action Step "Pulling Image" works locally in act, but not in action

### ISSUE THREAD

**Issue by tsabat** [whoan/docker-build-with-cache-action#62]
Hi, this action seems to do exactly what I want.  And it works via [act](https://github.com/nektos/act), but when I run it in github, the "Pulling Image" step seems to be skipped.  Am I doing something wrong?

Here's my stanza

```yml
      - name: Build Rails Image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          password: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          registry: xxx.dkr.ecr.us-west-2.amazonaws.com
          dockerfile: Dockerfile.phusion
          image_name: app-delete_me
          push_git_tag: true
          image_tag: 'latest,${{ github.run_number }}'
          pull_image_and_stages: true
          push_image_and_stages: true
```

In act (locally) the image pulls work

```
[Build/app_ecs] ⭐  Run Build Rails Image
[Build/app_ecs]   ☁  git clone 'https://github.com/whoan/docker-build-with-cache-action' # ref=v5
[Build/app_ecs]   🐳  docker build -t act-whoan-docker-build-with-cache-action-v5:latest /Users/timothysabat1/.cache/act/whoan-docker-build-with-cache-action@v5
[Build/app_ecs]   🐳  docker run image=act-whoan-docker-build-with-cache-action-v5:latest entrypoint=[] cmd=[]
| 
| [Action Step] Checking required input...
| 
| [Action Step] Log in to registry...
| WARNING! Your password will be stored unencrypted in /github/home/.docker/config.json.
| Configure a credential helper to remove this warning. See
| https://docs.docker.com/engine/reference/commandline/login/#credentials-store
| 
| Login Succeeded
| 
| 
| 
| [Action Step] Pulling image...
| 1: Pulling from app-delete_me-stages
| Digest: sha256:1b11a839f3bae988aaa7a467eebe63a3941b51db01233178e8efe8f290633a02
| 2: Pulling from app-delete_me-stages
| Digest: sha256:ad7097c938d2c0d2911803c5dfff38e3b143ad38e16997abad5747b4985e94f6
| 3: Pulling from app-delete_me-stages
| Digest: sha256:81f9625ab3b8b38d3545270817023334d41eaabc1975ae8c26a7602250f92794
| Status: Image is up to date for xxx.dkr.ecr.us-west-2.amazonaws.com/app-delete_me-stages
| xxx.dkr.ecr.us-west-2.amazonaws.com/app-delete_me-stages
| 
| [Action Step] Building image...
```

But when I run this in github, the image pull process seems not to happen.

![Screen Shot 2020-08-14 at 12 10 19](https://user-images.githubusercontent.com/636041/90284921-ab76c580-de27-11ea-85be-24a3e854bb58.png)
