### ISSUE TITLE
Cache with matrix builds

### ISSUE THREAD

**Issue by ylavoie** [whoan/docker-build-with-cache-action#66]
There should be a way to specify the cache repository name.
I'm trying to build this and only one gets cached
```
  postgres:
    strategy:
      matrix:
        version: ['9.5', '9.6', '10', '11', '12']
    needs: primary
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and push to Docker Hub
      uses: whoan/docker-build-with-cache-action@v5
      with:
        image_name: ${{ github.repository_owner }}/ledgersmb_circleci-postgres
        image_tag: ${{ matrix.version }}
        build_extra_args: "--build-arg postgres=${{ matrix.version }}"
        push_git_tag: true
        context: postgres
```
It could default to the current value but the user should be able to specify it.
