### ISSUE TITLE
Use new GitHub Container Registry

### ISSUE THREAD

**Issue by riker09** [whoan/docker-build-with-cache-action#68]
GitHub has released a second Registry, which currently is still in beta and only supports Docker images for now. See [official Migration Guide](https://docs.github.com/en/packages/getting-started-with-github-container-registry/migrating-to-github-container-registry-for-docker-images) for details.

I have tried pushing to it but ran into a timeout. Here's my workflow file (trimmed version):

```yaml
    - name: Build
      uses: whoan/docker-build-with-cache-action@v5
      with:
        image_name: my-image-name
        username: my-user-name
        registry: ghcr.io
        password: "${{ secrets.GHCR_TOKEN }}"
```

In the workflow logs I spotted this message: `The push refers to repository [ghcr.io/hetzner-dyndns]`. Looks like my username `my-user-name` is ignored.
