### ISSUE TITLE
support aws-actions

### ISSUE THREAD

**Issue by xenoterracide** [whoan/docker-build-with-cache-action#74]
you should be able to login to aws ecr using the official actions like this.

```yaml
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr
```
