### ISSUE TITLE
Is compose file extension supported?

### ISSUE THREAD

**Issue by MoSattler** [whoan/docker-build-with-cache-action#83]
Hi @whoan, great work on this action, it's super useful! Thanks a ton for this!

I am using multiple docker compose files in my CI.

For testing/linting etc:
```
docker-compose up
```

and for running my E2E tests and building the production images:
```
docker-compose -f docker-compose.yml -f docker-compose.production.yml up
```

For the latter, I am not sure how to specify the inheritance in the action. Basicly I want to do something like this
```
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          compose_file: docker-compose.yml, docker-compose.production.yml 
```

is anything like that possible?
