### ISSUE TITLE
Not working for AWS ECR: No images detected for registry (***.dkr.ecr.us-west-2.amazonaws.com)

### ISSUE THREAD

**Issue by tom10271** [whoan/docker-build-with-cache-action#84]
I got this `No images detected for registry (***.dkr.ecr.us-west-2.amazonaws.com)`

```yml
name: CI
on: push
jobs:
    test-installation:
        name: Test Odoo installation and migration scripts
        runs-on: ubuntu-latest
        steps:
            -   name: Configure AWS credentials
                uses: aws-actions/configure-aws-credentials@v1
                with:
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    aws-region: us-west-2

            -   name: Login to Amazon ECR
                id: login-ecr
                uses: aws-actions/amazon-ecr-login@v1

            -   name: Build Odoo image
                uses: whoan/docker-build-with-cache-action@v5
                with:
                    # Image URI in AWS is: 999999999.dkr.ecr.us-west-2.amazonaws.com/my-odoo-repo-name
                    registry: 999999999.dkr.ecr.us-west-2.amazonaws.com
                    image_name: my-odoo-repo-name
                    compose_file: docker-compose.yml

            -   name: Debugging with tmate
                uses: mxschmitt/action-tmate@v1.0.2
                if: failure()
```

What would be wrong? aws cli is working fine
