### ISSUE TITLE
Use container in next step of action

### ISSUE THREAD

**Issue by sam-hoffman** [whoan/docker-build-with-cache-action#85]
Is it possible to use the built/cached container in the next step of the github action?

Ideally, I'm hoping for something like this: 

```
name: aws-ecr

on: [push]

jobs:

  build-ecr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: whoan/docker-build-with-cache-action@v5
      with:
        username: "${{ secrets.AWS_ACCESS_KEY_ID }}"
        password: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        registry: 861729690598.dkr.ecr.us-west-1.amazonaws.com
        image_name: hello-world
  - name: Run tests
      uses: hello-world
      with:
        entrypoint: run test
```
Thanks in advance!
