### ISSUE TITLE
Two small bugs/assumptions in ./entrypoint.sh related to docker-compose

### ISSUE THREAD

**Issue by silky** [whoan/docker-build-with-cache-action#86]
Hey! Thanks so much for this plugin; it will be really handy :)

I'm trying to use it with a simple docker-compose file and I found that the script crashed in the this function: https://github.com/whoan/docker-build-with-cache-action/blob/master/entrypoint.sh#L66

The reason is twofold:

1. I had an underscore in my service-name, which your regex doesn't allow for:

```
version: "3.9"
services:
  test_thing:
    build: test_thing
    image: ghcr.io/...
```

2. i also didn't explicitly expand the `build` argument as the search expects (after changing the underscore):

```
version: "3.9"
services:
  test-thing:
    build:
      context: test-thing
      dockerfile: Dockerfile
    image: ghcr.io/...
```

in order to work around it i'll just fully-expand them; but maybe it could be added to the script to check for that? what are your thoughts? thanks! :)
