### ISSUE TITLE
build_extra_args json syntax does not handle multiple args

### ISSUE THREAD

**Issue by MaximeMYCS** [whoan/docker-build-with-cache-action#95]
Using this `Dockerfile`:

```
FROM ubuntu:20.04 as test_image
ARG BRANCH
ARG ENV_NAME
RUN echo "${BRANCH}"
RUN echo "${ENV_NAME}"
```

And this workflow:
```

name: Test
on:
  push:
    paths:
    - ".github/workflows/test.yml"
    - "build/Dockerfile"

jobs:
  build-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build test image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          image_name: test_image
          build_extra_args: '{"--build-arg": "BRANCH=foo", "--build-arg": "ENV_NAME=haha"}'
          dockerfile: build/Dockerfile
          push_image_and_stages: false
```

It seems that the build arguments are not passed correctly: only the last one is kept. Below is the docker command line issued from the run of this workflow.
```
docker build --tag my_awesome_image --file ./build/Dockerfile --build-arg ENV_NAME=haha .
```

Is it because of a wrong syntax in the `json` description of arguments ? It seems to be working fine for a single argument but I haven't been able to make it work for more than one.

Thanks for your help.
