### ISSUE TITLE
Push images and stages always pushed

### ISSUE THREAD

**Issue by ylavoie** [whoan/docker-build-with-cache-action#96]
Using this workflow:

```
name: Docker Image CI

on: [push, pull_request]

jobs:
  primary:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and push to Docker Hub
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_TOKEN }}
        image_name: ${{ github.repository_owner }}/ledgersmb_circleci-primary
        image_tag: latest
        context: primary
        push_git_tag: ${{ github.event_name == 'push' || github.event.pull_request.merged }}
        push_image_and_stages: ${{ github.event_name == 'push' || github.event.pull_request.merged }}
```

I'm finding that my images are always pushed on dockerhub on every PR.
Our processes allow test images for developer push on their forks but only on merges on the main repository. PR on main repository trigger the workflow but not the deployment of images, unless they are merged into master.

Please advise.
